### ISSUE TITLE
本地图片和视频怎么投屏呢

### ISSUE THREAD

**Issue by xzwgithub** [MQL9011/MRDLNA#11]

**Comment by MQL9011** [comment]
抱歉,目前只支持线上URL
本地的话, 除非手机作为 DRS 也就是服务节点, 才可以支持. 也就是手机自己起一个http服务.然后就会有URL.

**Comment by chiseller** [comment]
局域网搭建个视频服务器，然后取地址然后投屏？

**Comment by MQL9011** [comment]
@chiseller  是的, 只要是局域网内设备作为DRS也就是 服务器即可, 当然手机上起一个服务器也是可以的.

**Comment by chiseller** [comment]
@MQL9011 我在本地搞了一个nginx，然后开启目录访问，经测试效果并不是很好。不知道是不是我路由器的问题还是视频格式的问题。 网速出奇的慢。所以很奇怪是不是我nginx配置的问题。
