### ISSUE TITLE
iOS 14 UDPSocket 报错

### ISSUE THREAD

**Issue by zs1040466634** [MQL9011/MRDLNA#26]
1. 我使用模拟器是可以运行的
2. 我使用iOS14.6系统的真机会报错：[CLUPnPServer.m in line 118] => udpSocket关闭 
3. 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/23735986/124745282-3b4ac400-df52-11eb-8595-79363d947683.png">

**Comment by hewang1016729378** [comment]
怎么样，有没有找到解决方法？

**Comment by hewang1016729378** [comment]
怎么样，有没有找到解决方法？

**Comment by zs1040466634** [comment]
> 怎么样，有没有找到解决方法？

解决了，向苹果申请一个证书networking-multicast证书，具体可以参考这个：https://www.cnblogs.com/chao8888/p/13749383.html

**Comment by hewang1016729378** [comment]
需要重新打包上传嘛？

**Comment by zs1040466634** [comment]
> 需要重新打包上传嘛？

这个我不清楚，你可以试一下，我是用来研究的

**Comment by hewang1016729378** [comment]
很尴尬，向苹果申请权限，回复了一次邮件之后就没有后续了，这个方法你试过有效果吗？我能否加你QQ交流一下，1016729378

**Comment by zs1040466634** [comment]
> 很尴尬，向苹果申请权限，回复了一次邮件之后就没有后续了，这个方法你试过有效果吗？我能否加你QQ交流一下，1016729378

我申请大概近两周的时间，等待邮件的回复吧！或者多申请几次，成功后会有邮件的回复！
<img width="661" alt="image" src="https://user-images.githubusercontent.com/23735986/127252054-0713cf07-e75a-4558-b2bb-155db7517b5b.png">

**Comment by zs1040466634** [comment]
> 很尴尬，向苹果申请权限，回复了一次邮件之后就没有后续了，这个方法你试过有效果吗？我能否加你QQ交流一下，1016729378

我试了已经可以成功投屏了

**Comment by hewang1016729378** [comment]
能不能给我一个开发环境的调试证书，我试一下我这边，看看我边行不。
