### ISSUE TITLE
投屏失败

### ISSUE THREAD

**Issue by Zhumeng223** [MQL9011/MRDLNA#6]
投屏失败，显示下面的错误，该如何解决：

===========响应信息:<s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>501</errorCode><errorDescription>Action Failed</errorDescription></UPnPError></detail></s:Fault>

**Comment by MQL9011** [comment]
貌似是对方服务拒绝了这个操作
有可能这个设备不完全支持这套投屏协议

![image](https://user-images.githubusercontent.com/11871158/45790128-f1679500-bcb5-11e8-89ea-99f2d04884e7.png)

关于UPnP协议更多信息可以参考这个网址
https://www.iso.org/obp/ui/#iso:std:iso-iec:29341:-3-10:ed-1:v1:en:sec:5
