### ISSUE TITLE
投屏失败

### ISSUE THREAD

**Issue by xingwen93** [MQL9011/MRDLNA#8]
响应信息:<s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>501</errorCode><errorDescription>Action Failed</errorDescription></UPnPError></detail></s:Fault>

**Comment by MQL9011** [comment]
设备未响应
参考下
https://www.iso.org/obp/ui/#iso:std:iso-iec:29341:-3-10:ed-1:v1:en:sec:5
